-- Migration 003: Replace topics with dual tag system (auto + human)
-- Auto tags: generated by AI clustering, assigned by AI
-- Human tags: defined by users, assigned by AI or manually

-- 1. Create tags table (replaces topics)
create table tags (
  id uuid primary key default gen_random_uuid(),
  workspace_id text not null references workspaces(id),
  label text not null,
  description text,
  kind text not null check (kind in ('auto', 'human')),
  conversation_count int default 0,
  created_at timestamptz default now()
);

create index idx_tags_workspace on tags(workspace_id);
create index idx_tags_workspace_kind on tags(workspace_id, kind);

-- 2. Create conversation_tags junction (replaces message_topics)
create table conversation_tags (
  conversation_id uuid not null references conversations(id),
  tag_id uuid not null references tags(id) on delete cascade,
  assigned_by text not null check (assigned_by in ('ai', 'human')),
  confidence float,
  created_at timestamptz default now(),
  primary key (conversation_id, tag_id)
);

create index idx_conversation_tags_tag on conversation_tags(tag_id);
create index idx_conversation_tags_conv on conversation_tags(conversation_id);

-- 3. Drop old tables
drop table if exists message_topics;
drop table if exists topics;
